import type { Metadata } from "next";
import { Inter } from "next/font/google";
import NavBar from "@/components/layout/nav-bar";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body className={`${inter.className} relative`}>
        <NavBar />
        {children}
      </body>
    </html>
  );
}
